name: setup-rabbitmq-action
description: Set up RabbitMQ for testing
inputs:
  connection-string-name:
    description: The name of the environment variable to fill with the RabbitMQ connection string
    required: true
  tag:
    description: The name of the component RabbitMQ is being used for. The RabbitMQ namespace is tagged with this value.
    required: true
  host-env-var-name:
    description: The name of the environment variable to fill with the RabbitMQ host name
    required: false
  image-tag:
    description: The tag of the rabbitmq container image
    required: false
    default: 3-management

runs:
  using: node16
  main: dist/index.js
  post: dist/index.js