name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  ci:
    name: ${{ matrix.os.name }} - ${{ matrix.scenario.name }}
    runs-on: ${{ matrix.os.label }}
    strategy:
      matrix:
        os:
          - label: windows-latest
            name: Windows
          - label: ubuntu-latest
            name: Linux
        scenario:
          - name: default
            image-tag: 3-management
            host-env-var-name: RabbitHost
          - name: no-host-var
            image-tag: 3-management
            host-env-var-name: ''
          - name: custom-image-tag
            image-tag: 3.11-management
            host-env-var-name: ''
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Setup WSL
        uses: Particular/setup-wsl-action@v1.0.0
      - name: Run
        uses: ./
        with:
          connection-string-name: RabbitConnectionString
          host-env-var-name: ${{ matrix.scenario.host-env-var-name }}
          image-tag: ${{ matrix.scenario.image-tag }}
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Validate connection string
        shell: pwsh
        run: |
          echo "RabbitConnectionString = $($Env:RabbitConnectionString)"
          if ( $Env:RabbitConnectionString -le 0 ) {
            throw "Environment variable 'RabbitConnectionString' not set."
          }
      - name: Validate host var
        if: matrix.scenario.host-env-var-name != ''
        shell: pwsh
        run: |
          echo "RabbitHost = $($Env:RabbitHost)"
          if ( $Env:RabbitHost -le 0 ) {
            throw "Environment variable 'RabbitHost' not set."
          }
